-- MySQL Script generated by MySQL Workbench
-- Sat Oct  2 19:56:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Venta_motos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Venta_motos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Venta_motos` DEFAULT CHARACTER SET utf8 ;
USE `Venta_motos` ;

-- -----------------------------------------------------
-- Table `Venta_motos`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Venta_motos`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `genero` INT NOT NULL,
  `telefono` INT(7) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
